---
permalink: migrate/migrate-to-latest-ontaptools.html 
sidebar: sidebar 
keywords: migrate 
summary: Cuando se migran datos de almacenamiento, los back-ends de almacenamiento se incorporan manualmente mediante las API DE REST. Al migrar datos del proveedor VASA, los datos se exportan desde la base de datos de Derby existente e se importan a la base de datos MongoDB. 
---
= Migre desde ONTAP Tools para VMware vSphere 9.x a 10,2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se migran datos de almacenamiento, los back-ends de almacenamiento se incorporan manualmente mediante las API DE REST. Al migrar datos del proveedor VASA, los datos se exportan desde la base de datos de Derby existente e se importan a la base de datos MongoDB.


NOTE: Se recomienda migrar herramientas de ONTAP para la configuración de VMware vSphere 9.x solo si la configuración está prestando servicio solamente a la función del proveedor de VASA.


NOTE: Después de migrar desde las herramientas de ONTAP para VMware vSphere 9.x a 10,2, los almacenes de datos de vVols con protocolo NVMe/FC no funcionan porque las herramientas de ONTAP 10,2 solo admiten NVMe-oF con almacenes de datos VMFS.

*Acerca de esta tarea*

La migración es compatible con las herramientas de ONTAP para las versiones VMware vSphere 9.10D2, 9.11D4, 9.12D1 y 9.13D2 a la versión 10,2.


NOTE: Si utiliza las herramientas de ONTAP para la versión 9.13P1 de VMware vSphere, debe actualizar a 9.13D2 antes de la migración a la versión 10,2.


NOTE: Como usuario existente, debe realizar la copia de seguridad OVA de la versión actual antes de actualizar a las versiones de parches.



== Pasos de migración comunes

. Implemente OVA para herramientas de ONTAP para la versión VMware vSphere 10,2.
. Añada la instancia de vCenter Server que desee migrar a las herramientas de ONTAP para la versión de VMware vSphere 10,2. Consulte link:../configure/add-vcenter.html["Añada instancias de vCenter Server"]
. Back-end de almacenamiento incorporado localmente desde las herramientas de ONTAP para las API del complemento de VMware vSphere vCenter Server. Añada almacenamiento como almacenamiento de ámbito local para la migración.
. Los almacenes de datos de NFS y VMFS migrados desde las herramientas de ONTAP para VMware vSphere 9.xx solo se pueden ver en las herramientas de ONTAP para VMware vSphere 10,2 después de activar el trabajo de detección del almacén de datos, que puede demorar hasta 30 minutos en activarse. Compruebe si los almacenes de datos están visibles en la página Overview de la página de interfaz de usuario del complemento de ONTAP tools for VMware vSphere.




== Pasos de migración de SRA

*Antes de empezar*

Antes de migrar, asegúrese de que uno de los sitios esté en estado protegido y el otro en estado de recuperación.


NOTE: No migre si la recuperación tras fallos acaba de completarse y la nueva protección está pendiente. Complete la reprotección y, a continuación, lleve a cabo la migración. Lo mismo se aplica a la prueba del plan de recuperación. Una vez finalizada la prueba del plan de recuperación, limpie la recuperación de pruebas y, a continuación, inicie la migración.

. Realice los siguientes pasos para eliminar las herramientas de ONTAP para el adaptador SRA de la versión 9.xx de VMware vSphere en la IU de VMware Live Site Recovery:
+
.. Vaya a la página de gestión de VMware Live Site Recovery Configuration
.. Vaya a la sección Storage Replication Adapter
.. Haga clic en el menú de Kebab y haga clic en *Restablecer configuración*
.. Haga clic en el menú de Kebab y seleccione * Eliminar *
+
Lleve a cabo estos pasos en sitios de protección y recuperación.



. Instale herramientas de ONTAP para el adaptador SRA de VMware vSphere 10,2 en sitios tanto de protección como de recuperación siguiendo los pasos del link:../protect/configure-on-srm-appliance.html["Configurar el SRA en el dispositivo VMware Live Site Recovery"]
. En la página de interfaz de usuario de VMware Live Site Recovery, realice las operaciones de *Discover Arrays* y *Discover Devices* y verifique que los dispositivos se muestran como antes de la migración.




== Pasos para la migración del proveedor DE VASA

. Habilitar EL PUERTO 1527 de Derby en las herramientas existentes de ONTAP para VMware vSphere. Para habilitar el puerto, inicie sesión en la CLI con el usuario root y ejecute el siguiente comando:
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. Implemente OVA para herramientas de ONTAP para la versión VMware vSphere 10,2.
. Añada la instancia de vCenter Server que desee migrar a las herramientas de ONTAP para la versión de VMware vSphere 10,2. Consulte link:../configure/add-vcenter.html["Agregue una instancia de vCenter Server"].
. El back-end de almacenamiento incorporado localmente desde las API del complemento remoto de vCenter Server. Agregue almacenamiento como ámbito local para la migración.
. Emita la siguiente llamada API para migrar:
+
[]
====
*Método HTTP y punto final*

Esta llamada a la API de REST utiliza el siguiente método y extremo.

|===


| *Método HTTP* | *Ruta* 


| PUBLICAR | /api/v1 
|===
*Tipo de procesamiento*

Asíncrona

*Ejemplo de Curl*

/api/v1/vcenters/{vcguid}/migration-jobs

*Ejemplo de entrada JSON* Cuerpo de solicitud para migrar desde 9,12 y 9,13:

{ “otv_ip”: “10.12.13.45”, “vasa_provider_credentials”: { “username”: “vasauser”, “password”: “********” } “database_password”: “***********” }

Cuerpo de solicitud para otra migración de versiones:

{ “otv_ip”: “10.12.13.45”, “vasa_provider_credentials”: { “username”: “vasauser”, “password”: “********” }

*Ejemplo de salida JSON*

Se devuelve un objeto de trabajo. Debe guardar el identificador de trabajo para utilizarlo en el siguiente paso.

{ «id»: 123, «migration_id»: «d50073ce-35b4-4c51-9d2e-4ce66f802c35», «status»: «running» }

====
. Utilice el siguiente URI para comprobar el estado:
+
[listing]
----
https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true
----
+
Una vez completado el trabajo, valide el informe de migración. Puede ver el informe de la respuesta de trabajo como parte de los datos de trabajo.

. Añada las herramientas de ONTAP para el proveedor de almacenamiento VMware vSphere a vCenter Server y. link:../configure/registration-process.html["Registre el proveedor de VASA en vCenter Server"]
. Detenga el servicio de proveedor de almacenamiento VASA 9,10/9,11/9,12/9,13 de las herramientas de ONTAP para el proveedor de almacenamiento VMware vSphere desde la consola de mantenimiento.
+
No elimine el proveedor de VASA.

+
Una vez que se ha detenido el antiguo proveedor de VASA, vCenter Server conmuta al nodo de respaldo a las herramientas de ONTAP para VMware vSphere. Todos los almacenes de datos y máquinas virtuales son accesibles y se proporcionan desde las herramientas de ONTAP para VMware vSphere.

. Realice la migración de parches mediante la siguiente API:
+
[]
====
*Método HTTP y punto final*

Esta llamada a la API de REST utiliza el siguiente método y extremo.

|===


| *Método HTTP* | *Ruta* 


| PARCHE | /api/v1 
|===
*Tipo de procesamiento*

Asíncrona

*Ejemplo de Curl*

PARCHE «/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/84dr73bd-9173-65r7-w345-8ufdbb887d43

*Ejemplo de entrada JSON*

{ «id»: 123, «migration_id»: «d50073ce-35b4-4c51-9d2e-4ce66f802c35», «status»: «running» }

*Ejemplo de salida JSON*

Se devuelve un objeto de trabajo. Debe guardar el identificador de trabajo para utilizarlo en el siguiente paso.

{ «id»: 123, «migration_id»: «d50073ce-35b4-4c51-9d2e-4ce66f802c35», «status»: «running» }

El cuerpo de la solicitud está vacío para la operación de parche.


NOTE: uuid es el uuid de migración devuelto en la respuesta de la API posterior a la migración.

Una vez que la API de migración de parches se haya realizado correctamente, todas las máquinas virtuales cumplirán con la normativa de almacenamiento.

====
. La API de eliminación para la migración es:
+
[]
====
|===


| *Método HTTP* | *Ruta* 


| ELIMINAR | /api/v1 
|===
*Tipo de procesamiento*

Asíncrona

*Ejemplo de Curl*

/api/v1/vcenters/{vcguid}/migration-jobs/{migration_id}

Esta API elimina la migración por el ID de migración y elimina la migración en la instancia de vCenter Server dada.

====


Una vez realizada correctamente la migración y después de registrar las herramientas de ONTAP 10,2 en vCenter Server, haga lo siguiente:

* Actualice el certificado en todos los hosts.
* Espere un tiempo antes de realizar las operaciones de Datastore (DS) y Virtual Machine (VM). El tiempo de espera depende del número de hosts, DS y VM que estén presentes en la configuración. Cuando no espera, es posible que las operaciones fallen de forma intermitente.

