---
permalink: protect/map-folder.html 
sidebar: sidebar 
keywords:  
summary: Debe asignar sus carpetas en el sitio protegido y el sitio de recuperación para permitir la comunicación entre ellos. 
---
= Configure las asignaciones de carpetas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe asignar sus carpetas en el sitio protegido y el sitio de recuperación para permitir la comunicación entre ellos.

*Lo que necesitará*

Debe haber conectado los sitios protegidos y de recuperación.

* Pasos*

. Inicie sesión en vCenter Server y haga clic en *Site Recovery* > *Sites*.
. Seleccione su sitio protegido y haga clic en *Administrar*.
. En la ficha Administrar, seleccione *asignaciones de carpetas*.
. Seleccione el icono *Carpeta* para crear una nueva asignación de carpetas.
+
Aparece el asistente Crear asignación de carpetas.

. En el asistente Crear asignación de carpetas, realice lo siguiente:
+
.. Seleccione *Preparar automáticamente asignaciones para carpetas con nombres coincidentes* y haga clic en *Siguiente*.
.. Seleccione los objetos del centro de datos necesarios para los sitios protegidos y de recuperación y haga clic en *Agregar asignaciones*.
.. Haga clic en *Siguiente* después de crear correctamente las asignaciones.
.. Seleccione el objeto utilizado anteriormente para crear una asignación inversa y luego haga clic en *Finalizar*.




*resultado*

La página asignaciones de carpetas muestra los recursos del sitio protegido y los recursos del sitio de recuperación. Puede seguir los mismos pasos para otras redes del entorno.
