---
permalink: concepts/autosupport.html 
sidebar: sidebar 
keywords:  
summary: AutoSupport es un mecanismo que supervisa de forma proactiva el estado del sistema y envía automáticamente mensajes al soporte técnico de NetApp, su organización de soporte interno y un partner de soporte. 
---
= AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport es un mecanismo que supervisa de forma proactiva el estado del sistema y envía automáticamente mensajes al soporte técnico de NetApp, su organización de soporte interno y un partner de soporte.

De forma predeterminada, AutoSupport se habilita al configurar el sistema de almacenamiento por primera vez. AutoSupport comienza a enviar mensajes al soporte técnico 24 horas después de habilitar AutoSupport.

Puede habilitar o deshabilitar AutoSupport solo en el momento de la implementación. Se recomienda dejarlo activado. Al habilitar AutoSupport se agiliza la detección de problemas y se consigue una resolución más rápida. El sistema recopila información de AutoSupport y la almacena localmente, incluso cuando AutoSupport está desactivado. Sin embargo, no envía el informe a ninguna red. Debe incluir 216.240.21.18 // support.netapp.com URL en su red para una transmisión correcta.
