---
permalink: automation/overview-rest-apis.html 
sidebar: sidebar 
keywords: REST APIs, swagger 
summary: Describe cómo usar API de REST para realizar varias herramientas de ONTAP para operaciones de gestión de VMware vSphere. Las API DE REST se exponen a través de la página web de Swagger. 
---
= Información general de las API de REST
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las API de REST se pueden usar para realizar varias herramientas de ONTAP para operaciones de gestión de VMware vSphere. Las API DE REST se exponen a través de la página web de Swagger.

Es posible acceder a la página web de Swagger disponible en _\https://loadbalancerIP:8443/_ para ver la documentación de la API de REST, y también para emitir manualmente una llamada API.


NOTE: Todas las API tienen cuerpo de solicitud y ejemplos que se mencionan en la página de Swagger. Los flujos de trabajo y los ejemplos proporcionados en esta sección son solo para fines de referencia.



== Cómo acceder a las herramientas de ONTAP para la API de REST DE VMware vSphere

Es posible acceder a la API de REST de ONTAP de diferentes maneras.



== Consideraciones sobre la red

Es posible conectarse a la API DE REST a través de las siguientes interfaces:

* LIF de gestión de clústeres
* LIF de gestión de nodos
* LIF de gestión de SVM


La LIF que opta por utilizar debe configurarse para admitir el protocolo de gestión HTTPS. Además, la configuración del firewall en la red debe permitir el tráfico HTTPS.


NOTE: Siempre debe utilizar una LIF de gestión de clúster. Esto equilibrará la carga de las solicitudes de API en todos los nodos y evitará que los nodos estén desconectados o tengan problemas de conectividad. Si tiene configuradas varias LIF de gestión de clústeres, todas son equivalentes en cuanto al acceso a la API DE REST.



== Página de documentación en línea de las herramientas de ONTAP para la API de VMware vSphere

Puede acceder a Swagger desde el enlace de la página de soporte de las herramientas de NetApp ONTAP para el plugin de VMware vSphere.

El formato de la URL que se usa para acceder a la página de documentación de la versión más reciente de la API es:

`https://<loadbalancer_ip_address>/docs/api`



== Herramientas y software personalizados

Puede acceder a las herramientas de ONTAP para la API de VMware vSphere a través de cualquiera de las distintas herramientas y lenguajes de programación. Entre las opciones más populares se incluyen Python, Java, Curl y PowerShell. Programa, script o herramienta que usa la API actúa como cliente DE servicios web REST. El uso de un lenguaje de programación permite un conocimiento más profundo de la API y ofrece una oportunidad de automatizar las herramientas de ONTAP para la administración de VMware vSphere.

El formato de la URL básica que se usa para acceder directamente a la versión más reciente de la API es:

`https://<loadbalancer_ip_address>/api`

Para acceder a una versión específica de la API en la que se admiten varias versiones, el formato de la URL es:

`https://<loadbalancer_ip_address>/api/v1`



== Acceda a la documentación de referencia de las herramientas de ONTAP para la API de VMware vSphere a través de la interfaz de usuario de Swagger

Puede acceder a la documentación de la API de REST DE ONTAP a través de la interfaz de usuario de Swagger en el sistema ONTAP local.

*Antes de empezar*

Debe tener lo siguiente:

* La dirección IP o el nombre de host de la LIF de gestión de clústeres de ONTAP
* Nombre de usuario y contraseña de una cuenta con autoridad para acceder a la API DE REST DE ONTAP


.Pasos
. Escriba la URL en su navegador y presione *Enter*: _\https://<ip_address>/docs/api_
. Inicie sesión con la cuenta de ONTAP
+
La página de documentación de la API de ONTAP se muestra con las llamadas API organizadas en categorías de recursos principales en la parte inferior.

. Como ejemplo de una llamada individual a la API, desplácese hacia abajo hasta la categoría *cluster* y haga clic en *GET /cluster*.

