---
permalink: configure/add-vcenter.html 
sidebar: sidebar 
keywords:  
summary: 'Las instancias de vCenter Server son plataformas de gestión central que permiten controlar hosts, máquinas virtuales (VM) y back-ends de almacenamiento.' 
---
= Añada instancias de vCenter Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Añada instancias de vCenter Server a herramientas de ONTAP para VMware vSphere para configurar, gestionar y proteger sus almacenes de datos virtuales en el entorno de vCenter Server. Cuando agrega varias instancias de vCenter Server, se requieren certificados de CA personalizados para una comunicación segura entre las herramientas de ONTAP y cada vCenter Server.

*Acerca de esta tarea*

Puede añadir y gestionar varias instancias de vCenter Server con una instancia de herramientas de ONTAP para VMware vSphere.

* Pasos*

. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://loadBalanceIP:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione *vCenters* en la barra lateral.
. Seleccione *Añadir* para incorporar las instancias de vCenter Server y proporcione la dirección IP/nombre de host de vCenter, el nombre de usuario, la contraseña y los detalles de puerto.


Al añadir una instancia de vCenter Server a las herramientas de ONTAP, se ejecutan automáticamente las siguientes acciones:

* El plugin de cliente de vCenter está registrado
* Los privilegios personalizados de los plugins y las API se envían a la instancia de vCenter Server
* Se crean roles personalizados para gestionar los usuarios.


Cuando se añade una instancia de vCenter Server, las herramientas de ONTAP para el plugin de VMware vSphere se registran automáticamente en vCenter Server como plugin remoto. El plugin se puede ver en los métodos abreviados de la interfaz de usuario de vSphere.

El plugin está registrado con una clave _com.netapp.otv_ de la instancia de vCenter Server y se puede ver en ExtensionManager de la instancia de vCenter Server.
