---
permalink: configure/esxi-host-values.html 
sidebar: sidebar 
keywords:  
summary: Es posible configurar tiempos de espera y otros valores en los hosts ESXi mediante las herramientas de ONTAP para VMware vSphere con el fin de garantizar el mejor rendimiento y una conmutación al respaldo correcta. Los valores que las herramientas ONTAP para conjuntos de VMware vSphere se basan en las pruebas internas de NetApp. 
---
= Configure los valores de host ESXi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible configurar tiempos de espera y otros valores en los hosts ESXi mediante las herramientas de ONTAP para VMware vSphere con el fin de garantizar el mejor rendimiento y una conmutación al respaldo correcta. Los valores que las herramientas ONTAP para conjuntos de VMware vSphere se basan en las pruebas internas de NetApp.

Puede configurar los siguientes valores en un host ESXi:



== Configuración del adaptador de HBA/CNA

Establece los siguientes parámetros en los valores predeterminados:

* Disk.QFullSampleSize
* Disk.QFullThreshold
* Tiempos de espera de FC HBA de Emulex
* Tiempos de espera de HBA FC de QLogic




== Configuración DE MPIO

La configuración de MPIO define las rutas preferidas para los sistemas de almacenamiento de NetApp. La configuración de MPIO determina cuáles de las rutas disponibles están optimizadas (a diferencia de las rutas no optimizadas que atraviesan el cable de interconexión) y establece la ruta preferida en una de estas rutas.

En entornos de alto rendimiento, o cuando esté probando el rendimiento con un único almacén de datos LUN, considere la posibilidad de cambiar la configuración del equilibrio de carga de la política de selección de ruta (PSP) round-robin (VMW_PSP_RR) de la configuración de IOPS predeterminada de 1000 a un valor de 1.


NOTE: La configuración de MPIO no se aplica a los protocolos NVMe, NVMe/FC y NVMe/TCP.



== Configuración de NFS

* *Net.TcpipHeapSize*
+
Establezca este valor en 32.

* *Net.TcpipHeapMax*
+
Establezca este valor en 1024MB.

* *NFS.MaxVolumes*
+
Establezca este valor en 256.

* *NFS41.MaxVolumes*
+
Establezca este valor en 256.

* *NFS.MaxQueueDepth*
+
Defina este valor en 128 o superior para evitar cuellos de botella en cola.

* *NFS.HeartbeatMaxFailures*
+
Establezca este valor en 10 para todas las configuraciones de NFS.

* *NFS.HeartbeatFrequency*
+
Establezca este valor en 12 para todas las configuraciones de NFS.

* *NFS.HeartbeatTimeout*
+
Establezca este valor en 5 para todas las configuraciones de NFS.


