---
permalink: manage/delete-deployment.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: Después de eliminar las herramientas de ONTAP para la implementación de VMware vSphere, debe limpiar los volúmenes flexibles que se crearon durante la implementación. Si ha utilizado un clúster de ONTAP dedicado para las puestas en marcha, debe limpiar los volúmenes flexibles a medida que la puesta en marcha crea una gran cantidad de volúmenes flexibles que no se utilizan, lo que reduce el rendimiento. 
---
= Limpie los volúmenes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de eliminar las herramientas de ONTAP para la implementación de VMware vSphere, debe limpiar los volúmenes flexibles que se crearon durante la implementación. Si ha utilizado un clúster de ONTAP dedicado para las puestas en marcha, debe limpiar los volúmenes flexibles a medida que la puesta en marcha crea una gran cantidad de volúmenes flexibles que no se utilizan, lo que reduce el rendimiento.

Utilice las siguientes directrices para limpiar los volúmenes después de la eliminación de las herramientas de ONTAP para la puesta en marcha de VMware vSphere.

.Pasos
. Desde la máquina virtual del nodo principal de herramientas de ONTAP para VMware vSphere, ejecute el siguiente comando para identificar el tipo de puesta en marcha.
+
_cat /opt/netapp/meta/ansible_vars.yaml | grep -protocolo_

+
Si se trata de una implementación de iSCSI, también deberá eliminar iGroups.

. Recupere la lista de volúmenes flexibles creados en ONTAP durante la implementación con el siguiente comando.
+
_Kubectl describe persistentvolumes | grep InternalName | awk -F'=' '{print $2}'_

. Elimine máquinas virtuales de vCenter Server, consulte https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-27E53D26-F13F-4F94-8866-9C6CFA40471C.html["Quite VMs o VM Templates de vCenter Server o del almacén de datos"]
. Elimine volúmenes del administrador del sistema ONTAP, consulte https://docs.netapp.com/us-en/ontap/volumes/delete-flexvol-task.html["Eliminar un volumen de FlexVol"]. Dé el nombre exacto del FlexVolume en el comando de la cli para eliminar el volumen.
. En caso de implementación iSCSI, elimine los iGroups SAN de ONTAP, consulte https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["Consulte y gestione iniciadores E iGroups SAN"].
+
En una implementación de alta disponibilidad, se crean cuatro iGroups y, en una implementación no de alta disponibilidad, se crean dos iGroups. Ejecute el siguiente comando para buscar el primer nombre de igroup:

+
_Kubectl -n trident get tbc trident-backend -o yaml| grep igroupName: | awk -F':' '{print $2}'_

+
Los otros nombres de igroup comienzan con el nombre de host de la máquina virtual.


