---
permalink: manage/expand-storage-of-vvol-datastore.html 
sidebar: sidebar 
keywords: virtual volume datastores 
summary: Cuando hace clic con el botón derecho en el objeto de almacén de datos en la vista de objetos de vCenter, las acciones admitidas de las herramientas de ONTAP para VMware vSphere se muestran en la sección sobre plugins. 
---
= Expanda vVols Datastore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando hace clic con el botón derecho en el objeto de almacén de datos en la vista de objetos de vCenter, las acciones admitidas de las herramientas de ONTAP para VMware vSphere se muestran en la sección sobre plugins. Se habilitan acciones específicas según el tipo de almacén de datos y los privilegios de usuario actuales.

* Pasos*

. En la página de inicio de vSphere Client, haga clic en *hosts and Clusters*.
. En el panel de navegación, seleccione el centro de datos que contiene el almacén de datos.
. Haga clic con el botón derecho en el almacén de datos y seleccione *Herramientas de NetApp ONTAP* > *Añadir almacenamiento al almacén de datos*.
. En la ventana *crear o seleccionar volúmenes*, puede crear nuevos volúmenes o elegir entre los volúmenes existentes. La interfaz de usuario de se explica por sí misma. Siga las instrucciones según su elección.
. En la ventana *Resumen*, revise las selecciones y haga clic en *Expandir*. Puede realizar un seguimiento del progreso en el panel Tareas recientes.

