---
permalink: manage/storage-backend.html 
sidebar: sidebar 
keywords:  
summary: Los back-ends de almacenamiento son los sistemas que los hosts ESXi utilizan para el almacenamiento de datos. 
---
= Gestione los back-ends de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los back-ends de almacenamiento son los sistemas que los hosts ESXi utilizan para el almacenamiento de datos.



== Descubra el almacenamiento

Puede ejecutar la detección de un back-end de almacenamiento bajo demanda sin esperar a que una detección programada actualice los detalles del almacenamiento.

Siga estos pasos para detectar los back-ends de almacenamiento.

.Pasos
. Inicie sesión en el cliente de vSphere mediante `\https://vcenterip/ui`
. En la página de accesos directos, haga clic en *NetApp ONTAP tools* en la sección de plugins.
. En el panel izquierdo de las herramientas de ONTAP, navegue hasta *Backends de almacenamiento* y seleccione un backend de almacenamiento.
. Haga clic en el menú de elipses verticales y seleccione *Descubrir almacenamiento*


Puede realizar un seguimiento del progreso en el panel Tareas recientes.



== Modificar los back-ends de almacenamiento

Siga los pasos de esta sección para modificar un back-end de almacenamiento.

. Inicie sesión en el cliente de vSphere mediante `\https://vcenterip/ui`
. En la página de accesos directos, haga clic en *NetApp ONTAP tools* en la sección de plugins.
. En el panel izquierdo de las herramientas de ONTAP, navegue hasta *Backends de almacenamiento* y seleccione un backend de almacenamiento.
. Haga clic en el menú de puntos suspensivos verticales y seleccione *Modificar* para modificar las credenciales o el nombre del puerto. Puede realizar un seguimiento del progreso en el panel Tareas recientes.


Puede realizar la operación Modificar para clústeres de ONTAP globales mediante el Administrador de herramientas de ONTAP mediante los siguientes pasos.

. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://loadBalanceIP:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione los back-ends de almacenamiento en la barra lateral.
. Seleccione el backend de almacenamiento que desea modificar.
. Haga clic en el menú de elipses verticales y seleccione *Modificar*.
. Puede modificar las credenciales o el puerto. Introduzca el *Nombre de usuario* y *Contraseña* para modificar el backend de almacenamiento.




== Retire los back-ends de almacenamiento

Debe eliminar todos los almacenes de datos conectados al back-end de almacenamiento antes de quitar el back-end de almacenamiento. Siga los pasos que se indican a continuación para quitar un back-end de almacenamiento.

. Inicie sesión en el cliente de vSphere mediante `\https://vcenterip/ui`
. En la página de accesos directos, haga clic en *NetApp ONTAP tools* en la sección de plugins.
. En el panel izquierdo de las herramientas de ONTAP, navegue hasta *Backends de almacenamiento* y seleccione un backend de almacenamiento.
. Haga clic en el menú de elipses verticales y seleccione * Eliminar *. Asegúrese de que el back-end de almacenamiento no contenga ningún almacén de datos. Puede realizar un seguimiento del progreso en el panel Tareas recientes.


Puede realizar la operación de eliminación para clústeres de ONTAP globales mediante el Administrador de herramientas de ONTAP.

. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://loadBalanceIP:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione *Backends de almacenamiento* en la barra lateral.
. Seleccione el back-end de almacenamiento que desea quitar
. Haga clic en el menú de elipses verticales y seleccione * Eliminar *.




== Vista detallada del back-end de almacenamiento

La página del back-end de almacenamiento incluye todos los back-ends de almacenamiento. Puede realizar operaciones de detección de almacenamiento, modificación y eliminación en los back-ends de almacenamiento añadidos y no el secundario individual bajo el clúster.

Al hacer clic en el clúster primario o en el secundario bajo el back-end de almacenamiento, puede ver el resumen general del componente. Al hacer clic en el clúster principal, tiene la lista desplegable de acciones desde la que puede realizar las operaciones de detección, modificación y eliminación de almacenamiento. Esta opción no aparece al hacer clic en la SVM secundaria.

La página de resumen proporciona los siguientes detalles:

* Estado del back-end de almacenamiento
* Información de capacidad
* Información básica acerca de la máquina virtual
* Información de red como la dirección IP y el puerto de la red. Para la SVM secundaria, la información será la misma que el back-end del almacenamiento primario.
* Privilegios permitidos y restringidos para el back-end de almacenamiento. Para la SVM secundaria, la información será la misma que el back-end del almacenamiento primario. Los privilegios solo se muestran en los back-ends de almacenamiento basado en clúster. Si añade la SVM como back-end de almacenamiento, no se mostrará la información de privilegios.


La pestaña Interfaz proporciona información detallada sobre la interfaz.

El separador Niveles Locales proporciona información detallada sobre la lista de agregados.
